facebook_keys: &facebook
  facebook:
    app_id: '451465298229683'
    secret: 'dc9a7a789a9924ac8d30251351eb24e5'

google_analytics: &google_analytics
  google_analytics: 'UA-35563207-1'

development:
  <<: *facebook
  <<: *google_analytics

test:
  <<: *facebook
  <<: *google_analytics

production:
  <<: *facebook
  <<: *google_analytics
